# Generated by Django 5.0.6 on 2024-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription_subscription_unique_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.TextField(blank=True, null=True, verbose_name="id сессии"),
        ),
    ]
